import type { Metadata } from "next";
import "./globals.css";
import GsapSetup from "@/components/GsapSetup";

export const metadata: Metadata = {
  title: "MacBook GSAP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <GsapSetup />
        {children}
      </body>
    </html>
  );
}
